CREATE TABLE ARTIST_GENRE_XREF (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ARTIST_ID NOT NULL,
  GENRE_ID NOT NULL,
  UNIQUE(ARTIST_ID, GENRE_ID),
  FOREIGN KEY(ARTIST_ID) REFERENCES ARTIST(ID),
  FOREIGN KEY(GENRE_ID) REFERENCES GENRE(ID)
);
